services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - volume3:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  ondemand:
    container_name: ondemand
    image: rubbaboy/ondemand:v1.0.0-SNAPSHOT
    links:
      - db
    ports:
      - "8090:8090"
volumes:
  volume3: