services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password  --init-file /data/application/init.sql
    restart: always
    expose:
      - "3306"
    volumes:
      - volume:/var/lib/mysql
      - ./application:/data/application
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ondemand
  ondemand:
    container_name: ondemand
    image: rubbaboy/ondemand:v1.0.0-SNAPSHOT
    links:
      - db
    ports:
      - "8090:8090"
volumes:
  volume:

# mysql -h 127.0.0.1 -u root -pexample